# RefCOCO with BERT + DConv ResNet (direct projection)
# python train.py --batch_size 6 --lr_resnet 0.00001 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/refcoco_r50 --model_enc_vis resnet --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 6 --lr_resnet 0.00001 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/refcoco_r50 --model_enc_vis detr --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj

# RefCOCO with BERT + DETR(DConv ResNet backbone, direct projection) 
# python train.py --batch_size 6 --lr_resnet 0.00001 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/refcoco_r50 --model_enc_vis resnet --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 6 --lr_resnet 0.00001 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/refcoco_r50 --model_enc_vis detr --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj

# RefCOCO with Frozen BERT + DETR(Partial first_in_block DConv ResNet50 backbone, direct projection) 
# python train.py --batch_size 6 --lr_resnet 0.00001 --lr_bert 0 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/dconv_first_in_block_7x7_detr_resnet50_bert_k5 --model_enc_vis detr --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj --dconv_places first_in_block --dconv_7x7
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py --batch_size 6 --lr_resnet 0.00001 --lr_bert 0 --aug_crop --aug_scale --aug_translate --backbone resnet50 --detr_model ../../checkpoints/detr-r50-unc.pth --bert_enc_num 12 --detr_enc_num 6 --dataset unc --max_query_len 20 --output_dir outputs/dconv_first_in_block_7x7_detr_resnet50_bert_k5 --model_enc_vis detr --dataset_fraction 0.25 --use_dconv --dconv_weight_criteria direct_proj --dconv_places first_in_block --dconv_7x7
